name: API CI Tests
on: [push] 

jobs:
  test:
    runs-on: ubuntu-latest 
    steps:
      - uses: actions/checkout@v3
      
      - name: Node.js Kur
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Newman ve Raporlayıcıyı Yükle
        run: npm install -g newman newman-reporter-htmlextra

      - name: Testleri Koştur
        
        run: newman run products-collection.json -e dev-env.json -r cli,htmlextra

